export const Screens = {
  INIT: 'INIT',
  MAIN_APP: 'MAIN_APP',

  WELCOME: 'WELCOME',

  CATEGORIES: 'CATEGORIES',
  CAT_SEARCH: 'CAT_SEARCH',
  CAT_ORGANIZATIONS: 'CAT_ORGANIZATIONS',
  CAT_FILTER: 'CAT_FILTER',

  ORGANIZATION: 'ORGANIZATION',

  ORGANIZATION_MY: 'ORGANIZATION_MY',
  ORGANIZATION_CREATE: 'ORGANIZATION_CREATE',
  ORGANIZATION_REMOVE: 'ORGANIZATION_REMOVE',
  ORGANIZATION_EDIT: 'ORGANIZATION_EDIT',
  ORGANIZATION_PROMO: 'ORGANIZATION_PROMO',
  ORGANIZATION_PROMO_REMOVE: 'ORGANIZATION_PROMO_REMOVE',
  SUB_ORGANIZATION: 'SUB_ORGANIZATION',
  SUBSCRIBE_MODAL: 'SUBSCRIBE_MODAL',

  PROMOTIONS: 'PROMOTIONS',
  PROMO_FILTER: 'PROMO_FILTER',

  FAVORITIES: 'FAVORITIES',

  PROFILE: 'PROFILE',
  PROFILE_ADMIN: 'PROFILE_ADMIN',
  PROFILE_INFO: 'PROFILE_INFO',
  PROFILE_EDIT: 'PROFILE_EDIT',

  RECOVERY_MODAL: 'RECOVERY_MODAL',
  LOGOUT_MODAL: 'LOGOUT_MODAL',
  REMOVE_PROFILE_MODAL: 'REMOVE_PROFILE_MODAL',

  REVIEWS: 'REVIEWS',
  REVIEWS_CREATE: 'REVIEWS_CREATE',

  REPORT_MODAL: 'REPORT_MODAL',
  REPORT_CONFIRMED_MODAL: 'REPORT_CONFIRMED_MODAL',

  AUTH: 'AUTH',
  AUTH_ADMIN: 'AUTH_ADMIN',
  AUTH_CODE: 'AUTH_CODE',

  ADMIN_USERS: 'ADMIN_USERS',
  ADMIN_SERVICES: 'ADMIN_SERVICES',
  ADMIN_BANNERS: 'ADMIN_BANNERS',
  ADMIN_CREATE_BANNER: 'ADMIN_CREATE_BANNER',
  ADMIN_FINANCE: 'ADMIN_FINANCE',
  ADMIN_USER_ORGANIZATIONS: 'ADMIN_USER_ORGANIZATIONS',
};
