export const Screens = {
  INIT: 'INIT',
  MAIN_APP: 'MAIN_APP',

  CATEGORIES: 'CATEGORIES',
  CAT_SEARCH: 'CAT_SEARCH',
  CAT_ORGANIZATIONS: 'CAT_ORGANIZATIONS',
  CAT_FILTER: 'CAT_FILTER',

  ORGANIZATION: 'ORGANIZATION',

  ORGANIZATION_MY: 'ORGANIZATION_MY',
  ORGANIZATION_CREATE: 'ORGANIZATION_CREATE',
  ORGANIZATION_EDIT: 'ORGANIZATION_EDIT',
  ORGANIZATION_PROMO: 'ORGANIZATION_PROMO',
  ORGANIZATION_PROMO_REMOVE: 'ORGANIZATION_PROMO_REMOVE',

  PROMOTIONS: 'PROMOTIONS',
  PROMO_FILTER: 'PROMO_FILTER',

  FAVORITIES: 'FAVORITIES',

  PROFILE: 'PROFILE',
  PROFILE_INFO: 'PROFILE_INFO',
  PROFILE_EDIT: 'PROFILE_EDIT',

  RECOVERY_MODAL: 'RECOVERY_MODAL',
  LOGOUT_MODAL: 'LOGOUT_MODAL',
  REMOVE_PROFILE_MODAL: 'REMOVE_PROFILE_MODAL',
};
